name: Daily Digest

on:
  schedule:
    - cron: "20 6 * * *" # daily 06:20 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      - run: node scripts/daily-digest.mjs

      - name: Commit & push
        run: |
          git config user.name "hrco-bot"
          git config user.email "hrco-bot@users.noreply.github.com"
          git add data/ news/
          git commit -m "chore: daily digest" || exit 0
          git push